modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="bcc" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better Compatibility Checker" #mandatory
authors="Gaz" #optional
description='''
A better compatibility checker for Minecraft.
'''