modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="bcc" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better Compatability Checker" #mandatory
authors="Gaz" #optional
description='''
Im yet to do this
'''